Chuckslist::Application.routes.draw do
  match 'searches' => 'searches#index'
  match 'update_category/:id' => 'admin#update_category'
  match 'admin' => 'admin#index'
  match 'logout' => 'admin#destroy'
  match 'login' => 'admin#index'
  match 'password' => 'admin#pwd'
  match 'manager' => 'admin#manager'
  match 'authors' => 'admin#authors'
  match 'category' => 'admin#category'
  match 'user' => 'admin#user'
  match 'parent' => 'admin#parent_category'
  match 'feed' => 'ads#feed'
  match ':slug' => 'ads#list'
  match ':slug/feed' => 'ads#category_feed'
  match 'ads/destroy/:activation_hash' => 'ads#destroy', :via => 'post'
  match 'activate/:activation_hash' => 'ads#activate'
  match 'ads/edit/:activation_hash' => 'ads#edit'
  match 'ads/manage/:activation_hash' => 'ads#manage'
  match '/' => 'main#index'
  root :to => 'main#index'
  match '/:controller(/:action(/:id))'
end